[package]
name = "gpassword"
version = "0.1.0"
edition = "2024"

[dependencies]
age = "0.11.1"
clap = { version = "4.5.47", features = ["derive"] }
dirs = "6.0.0"
jiff = "0.2.15"
serde_json = "1.0.145"

[dev-dependencies]
tempfile = "3.8"
